### ISSUE TITLE
Site is down?

### ISSUE THREAD

**Issue by nashbridges** [clojure-goes-fast/clojure-goes-fast.com#2]
Just wanted to ping you in case you are not aware that http://clojure-goes-fast.com/ is ERR_ADDRESS_UNREACHABLE.

**Comment by nashbridges** [comment]
Whoops, it's down again

**Comment by alexander-yakushev** [comment]
Thanks again! I finally got the time to move the blog from the old CoreOS installation (which for some reason started leaking memory some time ago and caused all these outages) to a fresh Ubuntu install. Hopefully, this shouldn't happen again:) 🤞
