### ISSUE TITLE
Broken code formatting

### ISSUE THREAD

**Issue by sooheon** [clojure-goes-fast/clojure-goes-fast.com#3]
Seems like code blocks aren't formatting correctly, is this a perun issue?

http://clojure-goes-fast.com/blog/performance-nemesis-reflection/

**Comment by sooheon** [comment]
Weird, the issue fixed itself. Just took ~20s for the codeblock to render correctly.

**Comment by alexander-yakushev** [comment]
Thanks for noticing! The site loads CSS asynchronously (because I've read somewhere it's a good idea – probably not). In your case, it might have had a hiccup when loading it.
